-- Additive migration: existing news and guides remain unchanged.
BEGIN;
CREATE TABLE IF NOT EXISTS public.reviews (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 title text NOT NULL, subtitle text NOT NULL DEFAULT '', slug text NOT NULL UNIQUE,
 excerpt text NOT NULL DEFAULT '', content text NOT NULL DEFAULT '[]', image_url text NOT NULL DEFAULT '',
 category text NOT NULL DEFAULT 'Laptop', sku text NOT NULL DEFAULT '', specs jsonb NOT NULL DEFAULT '{}',
 published boolean NOT NULL DEFAULT false, featured boolean NOT NULL DEFAULT false,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), published_at timestamptz
);
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.reviews FROM anon, authenticated;
GRANT SELECT ON public.reviews TO anon, authenticated;
GRANT ALL ON public.reviews TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.reviews_id_seq TO service_role;
DROP POLICY IF EXISTS reviews_public_read ON public.reviews;
CREATE POLICY reviews_public_read ON public.reviews FOR SELECT TO anon, authenticated USING (published = true);
CREATE INDEX IF NOT EXISTS reviews_published_sort ON public.reviews(published, featured DESC, published_at DESC);
CREATE OR REPLACE FUNCTION public.set_review_dates() RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
 NEW.updated_at := now();
 IF NEW.published AND NEW.published_at IS NULL THEN NEW.published_at := now(); END IF;
 RETURN NEW;
END $$;
DROP TRIGGER IF EXISTS reviews_dates ON public.reviews;
CREATE TRIGGER reviews_dates BEFORE INSERT OR UPDATE ON public.reviews FOR EACH ROW EXECUTE FUNCTION public.set_review_dates();
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('review-images','review-images',true,8388608,ARRAY['image/jpeg','image/png','image/webp'])
ON CONFLICT(id) DO NOTHING;
COMMIT;
