import type {Metadata} from "next";
import Link from "next/link";
import {notFound} from "next/navigation";
import {cache} from "react";
import {publishedReviews} from "@/app/lib/reviews-server";
import {parseReviewBlocks} from "@/app/lib/reviews";
import {ReviewBody,ReviewSpecs} from "@/app/components/ReviewContent";
import ReviewCard from "@/app/components/ReviewCard";
export const dynamic="force-dynamic";
const getReview=cache(async(slug:string)=>(await publishedReviews(slug))[0]);
type Props={params:Promise<{slug:string}>};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const r=await getReview(slug);if(!r)return {title:"İnceleme bulunamadı",robots:{index:false}};return {title:r.title,description:r.excerpt||r.subtitle,alternates:{canonical:`https://donanimportali.com/incelemeler/${r.slug}`},openGraph:{type:"article",title:r.title,description:r.subtitle,publishedTime:r.published_at||r.created_at,modifiedTime:r.updated_at,images:r.image_url?[r.image_url]:[]}};}
export default async function ReviewPage({params}:Props){const {slug}=await params;const r=await getReview(slug);if(!r)notFound();const blocks=parseReviewBlocks(r.content);const headings=blocks.map((b,i)=>({...b,index:i})).filter(b=>b.type==="h2"||b.type==="h3");const related=(await publishedReviews()).filter(v=>v.id!==r.id).slice(0,3);
return <main className="max-w-6xl mx-auto px-4 sm:px-6 py-10"><nav className="text-xs text-zinc-500 mb-5"><Link href="/">Ana Sayfa</Link> / <Link href="/incelemeler">İncelemeler</Link> / {r.category}</nav><article><header className="rounded-3xl border border-zinc-800 bg-zinc-900/40 p-6 md:p-8"><p className="text-xs text-cyan-400 font-black uppercase">{r.category} incelemesi</p><h1 className="mt-4 text-3xl md:text-5xl font-black tracking-tight">{r.title}</h1>{r.subtitle&&<p className="mt-4 text-lg md:text-xl text-zinc-400">{r.subtitle}</p>}<time dateTime={r.published_at||r.created_at} className="block mt-5 text-xs text-zinc-500">{new Date(r.published_at||r.created_at).toLocaleDateString("tr-TR",{dateStyle:"long"})}</time></header>{r.image_url&&<img src={r.image_url} alt={r.title} className="mt-5 w-full max-h-[560px] object-cover rounded-3xl border border-zinc-800"/>}<ReviewSpecs specs={r.specs||{}}/><div className="grid lg:grid-cols-[minmax(0,1fr)_240px] gap-8"><ReviewBody blocks={blocks}/>{headings.length>0&&<aside className="hidden lg:block"><nav aria-label="İçindekiler" className="sticky top-24 border border-zinc-800 rounded-2xl p-5"><h2 className="font-black mb-4">İçindekiler</h2>{headings.map(b=><a key={b.index} href={`#bolum-${b.index}`} className="block py-2 text-sm text-zinc-400 hover:text-cyan-400">{b.value}</a>)}</nav></aside>}</div></article>{related.length>0&&<section className="mt-12"><h2 className="text-2xl font-black mb-5">Benzer İncelemeler</h2><div className="grid md:grid-cols-3 gap-5">{related.map(v=><ReviewCard key={v.id} review={v}/>)}</div></section>}</main>}
