"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowRight,Scale} from "lucide-react";
import type {ManualComparison} from "@/app/lib/manual-comparison";
export default function HomeComparison(){
  const [document,setDocument]=useState<ManualComparison|null>(null);
  useEffect(()=>{let active=true;void fetch("/api/laptop-comparison",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(active)setDocument(data.document||null)}).catch(()=>{});return()=>{active=false}},[]);
  if(!document)return null;
  const preview=document.rows.filter(row=>document.columns.some(col=>row.cells[col.id]?.value)).slice(0,3);
  return <section aria-labelledby="home-comparison-title" className="flex flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-3 px-1"><h2 id="home-comparison-title" className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-zinc-400"><Scale size={14} className="text-cyan-400"/>Karşılaştırma</h2><span className="text-[11px] font-medium text-zinc-600">Laptoplar yan yana</span></div><Link href="/laptop-karsilastirma" className="group relative overflow-hidden rounded-3xl border border-zinc-800 bg-gradient-to-br from-zinc-900 to-zinc-950 transition-all hover:border-cyan-500/40"><div className="flex min-h-[270px] flex-col justify-between p-7 md:p-8"><div className="flex items-center gap-2"><span className="rounded-lg bg-cyan-500 px-2.5 py-1 text-[10px] font-black uppercase text-zinc-950">Karşılaştırma</span><span className="text-xs text-zinc-500">{document.columns.length} laptop</span></div><div className="mt-9"><h3 className="text-2xl font-black leading-tight text-white group-hover:text-cyan-300 md:text-4xl">{document.title}</h3><p className="mt-3 text-sm text-zinc-300">{document.columns.map(col=>col.name).join(" · ")}</p>{preview.length>0&&<div className="mt-6 grid gap-2 sm:grid-cols-3">{preview.map(row=><div key={row.id} className="rounded-xl border border-zinc-800 bg-zinc-950/60 p-3"><span className="text-[10px] font-bold uppercase text-zinc-500">{row.label}</span><div className="mt-1 space-y-1">{document.columns.map(col=><p key={col.id} className={`line-clamp-1 text-xs ${row.cells[col.id]?.highlighted?"font-black text-cyan-300":"text-zinc-300"}`}>{row.cells[col.id]?.value||"Belirtilmedi"}</p>)}</div></div>)}</div>}</div></div></Link><div className="flex justify-end pt-1"><Link href="/laptop-karsilastirma" className="inline-flex items-center gap-2 rounded-xl border border-zinc-800 bg-zinc-900/60 px-4 py-3 text-xs font-black text-zinc-200 transition-all hover:border-cyan-500/30 hover:text-cyan-400">Karşılaştırmayı gör <ArrowRight size={14}/></Link></div></section>;
}
