"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowRight,Laptop,Scale} from "lucide-react";
import type {ManualComparison} from "@/app/lib/manual-comparison";
export default function HomeComparison(){
  const [document,setDocument]=useState<ManualComparison|null>(null);
  useEffect(()=>{let active=true;void fetch("/api/laptop-comparison",{cache:"no-store"}).then(response=>response.json()).then(data=>{if(active)setDocument(data.document||null)}).catch(()=>{});return()=>{active=false}},[]);
  if(!document)return null;
  return <section aria-labelledby="home-comparison-title" className="flex flex-col gap-4"><div className="flex flex-wrap items-center justify-between gap-3 px-1"><h2 id="home-comparison-title" className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-zinc-400"><Scale size={14} className="text-cyan-400"/>Karşılaştırma</h2><span className="text-[11px] font-medium text-zinc-600">Laptoplar yan yana</span></div><Link href="/laptop-karsilastirma" className="group relative overflow-hidden rounded-3xl border border-zinc-800 bg-gradient-to-br from-zinc-900 to-zinc-950 transition-all hover:border-cyan-500/40"><div className="p-6 md:p-8"><span className="rounded-lg bg-cyan-500 px-2.5 py-1 text-[10px] font-black uppercase text-zinc-950">Karşılaştırma</span><h3 className="mt-5 text-2xl font-black leading-tight text-white group-hover:text-cyan-300 md:text-4xl">{document.title}</h3><div className="mt-7 flex flex-wrap items-stretch justify-center gap-2 sm:flex-nowrap sm:gap-3">{document.columns.map((col,index)=><div key={col.id} className="flex min-w-0 flex-1 items-center gap-2 sm:gap-3">{index>0&&<span className="shrink-0 rounded-full border border-cyan-500/40 bg-cyan-500/10 px-2 py-1 text-xs font-black text-cyan-300">VS</span>}<div className="min-w-0 flex-1 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-3 text-center"><div className="flex h-32 items-center justify-center overflow-hidden rounded-xl bg-white sm:h-40">{col.imageUrl?<img src={col.imageUrl} alt={col.name} className="h-full w-full object-contain" loading="lazy"/>:<Laptop size={38} className="text-zinc-400"/>}</div><p className="mt-3 break-words text-xs font-black leading-5 text-white sm:text-sm">{col.name}</p></div></div>)}</div></div></Link><div className="flex justify-end pt-1"><Link href="/laptop-karsilastirma" className="inline-flex items-center gap-2 rounded-xl border border-zinc-800 bg-zinc-900/60 px-4 py-3 text-xs font-black text-zinc-200 transition-all hover:border-cyan-500/30 hover:text-cyan-400">Karşılaştırmayı gör <ArrowRight size={14}/></Link></div></section>;
}
