"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Plus,Save,Scale,Trash2} from "lucide-react";
import {emptyComparison,type ManualComparison} from "@/app/lib/manual-comparison";
type Review={slug:string;title:string};
const input="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-3 py-2.5 text-sm text-white outline-none focus:border-cyan-400";
export default function ComparisonAdmin() {
  const [document,setDocument]=useState<ManualComparison>(emptyComparison());
  const [reviews,setReviews]=useState<Review[]>([]);
  const [message,setMessage]=useState("");
  const [busy,setBusy]=useState(false);
  useEffect(()=>{void (async()=>{try{const response=await fetch("/api/admin/laptop-comparison",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"Yüklenemedi.");setDocument(data.document);setReviews(data.reviews||[]);}catch(error){setMessage(error instanceof Error?error.message:"Yüklenemedi.");}})()},[]);
  const update=(fn:(current:ManualComparison)=>ManualComparison)=>setDocument(current=>fn(structuredClone(current)));
  const addColumn=()=>update(current=>{if(current.columns.length===3)return current;const id=`laptop-${current.columns.length+1}`;current.columns.push({id,name:"",reviewSlug:""});current.rows.forEach(row=>{row.cells[id]={value:"",highlighted:false}});return current});
  const removeColumn=()=>update(current=>{if(current.columns.length!==3)return current;const removed=current.columns.pop();if(removed)current.rows.forEach(row=>{delete row.cells[removed.id]});return current});
  const addRow=()=>update(current=>{const id=`feature-${Date.now()}`;current.rows.push({id,label:"",cells:Object.fromEntries(current.columns.map(col=>[col.id,{value:"",highlighted:false}]))});return current});
  const save=async()=>{setBusy(true);setMessage("");try{const response=await fetch("/api/admin/laptop-comparison",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify(document)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Kaydedilemedi.");setDocument(data.document);setMessage(data.document.published?"Karşılaştırma yayında.":"Taslak kaydedildi.");}catch(error){setMessage(error instanceof Error?error.message:"Kaydedilemedi.");}finally{setBusy(false)}};
  return <main className="min-h-screen bg-zinc-950 px-4 py-10 text-white"><div className="mx-auto max-w-7xl"><Link href="/yonetim" className="inline-flex items-center gap-2 text-xs text-zinc-400 hover:text-cyan-400"><ArrowLeft size={15}/>Yönetim merkezine dön</Link><div className="mt-7 flex items-center gap-3"><Scale size={29} className="text-cyan-400"/><div><p className="text-[11px] font-bold uppercase tracking-widest text-cyan-400">Manuel karşılaştırma</p><h1 className="text-3xl font-black">Laptop karşılaştırması</h1></div></div><p className="mt-3 text-sm leading-6 text-zinc-400">Model adlarını ve özellikleri elle gir. Üstün gördüğün değerin yanındaki kutuyu işaretle; ziyaretçi o değeri vurgulu görür.</p>
    <div className="mt-7 flex flex-wrap items-end justify-between gap-3"><label className="w-full max-w-xl text-xs font-bold text-zinc-300">Karşılaştırma başlığı<input value={document.title} onChange={e=>update(current=>{current.title=e.target.value;return current})} className={`mt-2 ${input}`}/></label><div className="flex gap-2"><button type="button" onClick={addColumn} disabled={document.columns.length===3} className="inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm font-bold hover:border-cyan-400 disabled:opacity-40"><Plus size={16}/>Sütun ekle</button>{document.columns.length===3&&<button type="button" onClick={removeColumn} className="rounded-xl border border-zinc-700 px-3 text-xs text-rose-300">Üçüncü sütunu kaldır</button>}</div></div>
    <div className="mt-5 max-w-full overflow-x-auto rounded-2xl border border-zinc-800 bg-zinc-900/40"><table className="w-full min-w-[760px] border-collapse text-left"><thead><tr className="bg-zinc-900"><th className="w-48 border-b border-r border-zinc-800 p-3 text-xs text-zinc-400">Donanım özelliği</th>{document.columns.map((col,index)=><th key={col.id} className="min-w-64 border-b border-r border-zinc-800 p-3 last:border-r-0"><span className="text-[10px] uppercase tracking-wide text-zinc-500">Laptop {index+1}</span><input value={col.name} onChange={e=>update(current=>{current.columns[index].name=e.target.value;return current})} className={`mt-1 ${input}`} placeholder="Tam model adı"/></th>)}</tr></thead><tbody>{document.rows.map((row,rowIndex)=><tr key={row.id} className="border-b border-zinc-800/70"><td className="border-r border-zinc-800 p-2"><div className="flex items-center gap-1"><input aria-label={`Özellik ${rowIndex+1}`} value={row.label} onChange={e=>update(current=>{current.rows[rowIndex].label=e.target.value;return current})} className={input} placeholder="Özellik adı"/><button type="button" onClick={()=>update(current=>{current.rows.splice(rowIndex,1);return current})} aria-label={`${row.label||"Satır"} satırını sil`} className="p-1 text-zinc-600 hover:text-rose-300"><Trash2 size={14}/></button></div></td>{document.columns.map(col=><td key={col.id} className="border-r border-zinc-800 p-2 last:border-r-0"><div className="flex items-center gap-2"><input aria-label={`${row.label} ${col.name||col.id} değeri`} value={row.cells[col.id]?.value||""} onChange={e=>update(current=>{current.rows[rowIndex].cells[col.id].value=e.target.value;return current})} className={`${input} min-w-0`} placeholder="Değeri yaz"/><label title="Kâğıt üzerinde üstün göster" className="flex shrink-0 items-center gap-1 text-xs text-zinc-400"><input type="checkbox" aria-label={`${row.label} ${col.name||col.id} üstün göster`} checked={row.cells[col.id]?.highlighted||false} onChange={e=>update(current=>{current.rows[rowIndex].cells[col.id].highlighted=e.target.checked;return current})} className="h-4 w-4 accent-cyan-400"/>✓</label></div></td>)}</tr>)}</tbody><tfoot><tr><th className="border-r border-zinc-800 p-3 text-xs text-zinc-400">İnceleme bağlantısı</th>{document.columns.map((col,index)=><td key={col.id} className="border-r border-zinc-800 p-3 last:border-r-0"><select aria-label={`Laptop ${index+1} incelemesi`} value={col.reviewSlug} onChange={e=>update(current=>{current.columns[index].reviewSlug=e.target.value;return current})} className={input}><option value="">İnceleme seç</option>{reviews.map(review=><option key={review.slug} value={review.slug}>{review.title}</option>)}</select></td>)}</tr></tfoot></table></div>
    <button type="button" onClick={addRow} className="mt-4 inline-flex items-center gap-2 rounded-xl border border-zinc-700 px-4 py-2.5 text-sm font-bold hover:border-cyan-400"><Plus size={16}/>Özellik satırı ekle</button><div className="mt-7 flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={document.published} onChange={e=>update(current=>{current.published=e.target.checked;return current})} className="h-4 w-4 accent-cyan-400"/>Karşılaştırmayı yayınla</label><button type="button" disabled={busy} onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-cyan-400 px-5 py-3 text-sm font-black text-zinc-950 hover:bg-cyan-300 disabled:opacity-50"><Save size={16}/>{busy?"Kaydediliyor...":"Kaydet"}</button><Link href="/laptop-karsilastirma" className="text-sm font-bold text-cyan-400">Sayfayı gör →</Link></div>{message&&<p role="status" className="mt-4 text-sm text-cyan-300">{message}</p>}</div></main>;
}
