"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {ArrowRight, Laptop2, Scale, CheckCircle2} from "lucide-react";
import {compareLaptops, type Laptop} from "./comparison";

export default function ComparisonClient({initialLaptops:laptops}:{initialLaptops:Laptop[]}) {
  const [leftId,setLeftId] = useState(laptops[0]?.id || "");
  const [rightId,setRightId] = useState(laptops[1]?.id || "");
  useEffect(()=>{
    const params = new URLSearchParams(window.location.search);
    const a = params.get("a") || "", b = params.get("b") || "";
    setLeftId(laptops.some(item=>item.id===a) ? a : laptops[0]?.id || "");
    setRightId(laptops.some(item=>item.id===b && item.id!==a) ? b : laptops.find(item=>item.id!==a && item.id!==laptops[0]?.id)?.id || laptops[1]?.id || "");
  },[laptops]);
  const left = laptops.find(item=>item.id===leftId);
  const right = laptops.find(item=>item.id===rightId);
  const rows = useMemo(()=>left && right && left.id!==right.id ? compareLaptops(left,right) : [],[left,right]);
  useEffect(()=>{ if (!left || !right || left.id===right.id) return; const url = new URL(window.location.href); url.searchParams.set("a",left.id);url.searchParams.set("b",right.id);window.history.replaceState(null,"",url); },[left,right]);
  const chooseLeft=(id:string)=>{setLeftId(id);if(id===rightId)setRightId(laptops.find(item=>item.id!==id)?.id||"")};
  const chooseRight=(id:string)=>{setRightId(id);if(id===leftId)setLeftId(laptops.find(item=>item.id!==id)?.id||"")};
  const featureRows = rows.filter(row=>row.stronger);
  return <main className="mx-auto max-w-6xl px-4 py-10 text-zinc-100 sm:px-6 sm:py-14">
    <div className="mb-7"><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-cyan-400"><Scale size={16}/> Laptop karşılaştırma</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">İki laptopu yan yana incele</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-zinc-400">Yayımladığımız incelemelerdeki modellerin önemli teknik farklarını gör. Vurgular yalnızca karşılaştırılabilir özelliklerde kâğıt üstündeki farkı gösterir.</p></div>
    {laptops.length<2 && <div className="rounded-3xl border border-zinc-800 bg-zinc-900/50 p-8"><Laptop2 className="text-cyan-400" size={28}/><h2 className="mt-4 text-xl font-bold">İlk karşılaştırmalar hazırlanıyor</h2><p className="mt-2 text-sm text-zinc-400">Kataloğa iki incelenmiş laptop eklendiğinde burada karşılaştırabileceksin.</p><Link href="/incelemeler" className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-cyan-400">İncelemelere göz at <ArrowRight size={15}/></Link></div>}
    {left && right && left.id!==right.id && <>
      <section className="grid grid-cols-2 gap-2 sm:gap-5" aria-label="Karşılaştırılacak laptoplar">{[[left,chooseLeft],[right,chooseRight]].map(([item,choose],index)=>{const laptop=item as Laptop;const onChoose=choose as (id:string)=>void;return <article key={index} className="min-w-0 rounded-2xl border border-zinc-800 bg-zinc-900/60 p-3 sm:rounded-3xl sm:p-5"><label className="block text-[11px] font-bold uppercase tracking-wide text-zinc-500" htmlFor={`laptop-${index}`}>{index===0?"İlk laptop":"İkinci laptop"}</label><select id={`laptop-${index}`} value={laptop.id} onChange={e=>onChoose(e.target.value)} className="mt-2 w-full rounded-xl border border-zinc-700 bg-zinc-950 px-2 py-2.5 text-xs font-semibold text-white sm:px-3 sm:text-sm">{laptops.map(option=><option key={option.id} value={option.id}>{option.model}</option>)}</select><div className="mt-4 flex h-32 items-center justify-center overflow-hidden rounded-xl bg-zinc-950 sm:h-52">{laptop.image_url?<img src={laptop.image_url} alt={laptop.model} className="h-full w-full object-contain"/>:<Laptop2 size={40} className="text-zinc-700"/>}</div><p className="mt-4 text-[10px] font-bold uppercase tracking-widest text-cyan-400">{laptop.brand}</p><h2 className="mt-1 min-h-12 text-sm font-black leading-5 sm:min-h-14 sm:text-xl">{laptop.model}</h2>{laptop.review_slug && <Link href={`/incelemeler/${encodeURIComponent(laptop.review_slug)}`} className="mt-3 inline-flex items-center gap-1 text-xs font-bold text-cyan-400 hover:text-cyan-200 sm:text-sm">İncelemeyi oku <ArrowRight size={14}/></Link>}</article>})}</section>
      {featureRows.length>0 && <section className="mt-6 rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-4 sm:p-6"><h2 className="flex items-center gap-2 text-base font-black"><CheckCircle2 size={18} className="text-cyan-400"/>Kâğıt üzerinde öne çıkan farklar</h2><div className="mt-3 flex flex-wrap gap-2">{featureRows.slice(0,6).map(row=><span key={row.label} className="rounded-full border border-zinc-700 bg-zinc-950/80 px-3 py-1.5 text-[11px] text-zinc-200"><strong className="text-cyan-400">{row.stronger==="left"?left.model:right.model}</strong> · {row.label}</span>)}</div></section>}
      <section className="mt-6 overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900/50"><div className="grid grid-cols-[minmax(0,1fr)_minmax(0,1fr)] border-b border-zinc-800 bg-zinc-900 px-3 py-3 text-[11px] font-black sm:grid-cols-[180px_minmax(0,1fr)_minmax(0,1fr)] sm:px-5 sm:text-sm"><span className="hidden text-zinc-500 sm:block">Özellik</span><span className="truncate pr-2">{left.model}</span><span className="truncate">{right.model}</span></div>{[...new Set(rows.map(row=>row.group))].map(group=><div key={group}><h3 className="border-y border-zinc-800 bg-zinc-950/70 px-3 py-2 text-xs font-bold uppercase tracking-wider text-cyan-400 sm:px-5">{group}</h3>{rows.filter(row=>row.group===group).map(row=><div key={row.label} className="grid grid-cols-2 gap-x-3 gap-y-1 border-b border-zinc-800/70 px-3 py-3 last:border-b-0 sm:grid-cols-[180px_minmax(0,1fr)_minmax(0,1fr)] sm:px-5"><span className="col-span-2 text-[11px] font-semibold text-zinc-500 sm:col-span-1 sm:text-xs">{row.label}</span><span className={`min-w-0 break-words text-xs leading-5 sm:text-sm ${row.stronger==="left"?"font-extrabold text-cyan-300":"text-zinc-200"}`}>{row.left}</span><span className={`min-w-0 break-words text-xs leading-5 sm:text-sm ${row.stronger==="right"?"font-extrabold text-cyan-300":"text-zinc-200"}`}>{row.right}</span></div>)}</div>)}</section><p className="mt-4 text-xs leading-5 text-zinc-500">Turkuaz değerler yalnızca teknik özellikteki karşılaştırılabilir farkı belirtir. Pil kapasitesi kullanım süresi, ekran kartı watt değeri oyun performansı anlamına gelmez. İşlemci ve ekran kartı yalnızca doğrulanmış editör sırası girildiğinde vurgulanır.</p>
    </>}
  </main>;
}
